name: bump-chart-version
on:
  workflow_dispatch:
    inputs:
      chart_path:
        description: 'Path to chart'
        required: true
        type: string
      new_version:
        description: 'New version (e.g. 1.2.3 or 1.2.3-rc1)'
        required: true
        type: string

jobs:
