name: bump-version

on:
  workflow_dispatch:
    inputs:
      chart_dir:
        description: 'Directory of the chart (inside charts)'
        required: true
        type: string
      new_version:
        description: 'New version (e.g. 1.2.3 or 1.2.3-rc1)'
        required: true
        type: string

permissions:
  contents: write  # for creating PRs and pushing changes
  pull-requests: write  # for opening PRs

jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'robinlioret/helm-charts' }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: |
          chmod +x ./hacks/bump-version.sh
          ./hacks/bump-version.sh charts ${{ github.event.inputs.chart_dir }} ${{ github.event.inputs.new_version }}
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e
        with:
          commit-message: "chart: ${{ github.event.inputs.chart_dir }} bump version to ${{ github.event.inputs.new_version }}"
          title: "chart: ${{ github.event.inputs.chart_dir }} bump version to ${{ github.event.inputs.new_version }}"
          body: "Automated PR to bump versions."
          branch: "bump-version/${{ github.event.inputs.chart_dir }}/v${{ github.event.inputs.new_version }}"
          delete-branch: true
