name: release

on:
  push:
    branches:
      - main
#    paths:
#      - 'charts/**/Chart.yaml'

jobs:
  detect-charts:
    runs-on: ubuntu-latest
    if: |
      ${{github.repository == 'robinlioret/helm-charts' }}
    permissions:
      contents: read
    outputs:
      charts: ${{ steps.charts.outputs.charts }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Detect charts
        id: charts
        run: |
          echo "charts=[\"$(ls -m charts | sed 's/, /", "/g')\"]" >> $GITHUB_OUTPUT

      - name: Show charts
        id: debug
        run: |
          echo "${{ steps.charts.outputs.charts }}"

  release:
    runs-on: ubuntu-latest
    if: |
      ${{github.repository == 'robinlioret/helm-charts' }}
    permissions:
      contents: write
    needs: detect-charts
    strategy:
      matrix:
        chart: ${{ fromJson(needs.detect-charts.outputs.charts) }}
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f #v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts/${{ matrix.chart }}

